import {
  LayoutDashboard,
  FileText,
  Search,
  Settings,
  Brain,
  MessageSquare,
  Share2,
  FlaskConical,
  BarChart3,
  Activity,
  Heart,
  Plus,
  Clock,
  Upload,
  List,
  Layers,
  Network,
  Users,
  AlertTriangle,
  Sliders,
  Cpu,
  ArrowUpDown,
  FolderSearch,
  Sparkles,
  Library,
  Award,
  Bookmark,
  CircleHelp,
  ClipboardCheck,
  UserRoundSearch,
  FolderCog,
  MessagesSquare,
  Hash,
  ClipboardList,
  UserCheck,
  Building2,
  CalendarDays,
  CircleDollarSign,
  Flag,
  FolderKanban,
  Link2,
  FileClock,
  GitBranch,
  Workflow,
  ShieldCheck,
  Bell,
  Box,
  Server,
  Calendar,
  Mail,
  Truck,
  Trash2,
  Megaphone,
  User,
  Globe,
  MessageSquarePlus,
  History,
  Plane,
  Package,
  MonitorCog,
  Boxes,
  Warehouse,
  CalendarClock,
  LayoutGrid,
  MapPin,
  Phone,
  StickyNote,
  Contact,
  Send,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { DEFAULT_AUTHENTICATED_PATH } from '../utils/authNavigation';
import { departmentConfigs } from '../config/departments';

export interface SubMenuItem {
  labelKey: string;
  icon: LucideIcon;
  to: string;
}

export interface NavItem {
  to: string;
  icon: LucideIcon;
  labelKey: string;
  children: SubMenuItem[];
}

export const navItems: NavItem[] = [
  {
    to: '/cortex',
    icon: LayoutDashboard,
    labelKey: 'nav.workspace',
    children: [
      { labelKey: 'nav.workspace.aiDocumentQuery', icon: Sparkles, to: DEFAULT_AUTHENTICATED_PATH },
      { labelKey: 'nav.dashboard.enterpriseSystems', icon: Server, to: '/cortex/dashboard/enterprise-systems' },
      { labelKey: 'nav.dashboard.overview', icon: BarChart3, to: '/cortex/dashboard' },
      { labelKey: 'nav.dashboard.health', icon: Heart, to: '/cortex/dashboard/health' },
      { labelKey: 'nav.dashboard.activity', icon: Activity, to: '/cortex/dashboard/activity' },
    ],
  },
  {
    to: '/cortex/workspace',
    icon: UserRoundSearch,
    labelKey: 'nav.personalWorkspace',
    children: [
      { labelKey: 'nav.personalWorkspace.tasks', icon: ClipboardList, to: '/cortex/workspace/tasks' },
      { labelKey: 'nav.personalWorkspace.announcements', icon: Megaphone, to: '/cortex/workspace/announcements' },
      { labelKey: 'nav.personalWorkspace.status', icon: User, to: '/cortex/workspace/status' },
      { labelKey: 'nav.personalWorkspace.following', icon: Bookmark, to: '/cortex/workspace/following' },
      { labelKey: 'nav.personalWorkspace.review', icon: ClipboardCheck, to: '/cortex/workspace/review' },
      { labelKey: 'nav.personalWorkspace.points', icon: Award, to: '/cortex/workspace/points' },
      { labelKey: 'nav.personalWorkspace.projects', icon: FolderKanban, to: '/cortex/workspace/projects' },
      { labelKey: 'nav.personalWorkspace.phoneRecords', icon: Phone, to: '/cortex/workspace/phone-records' },
      { labelKey: 'nav.personalWorkspace.memos', icon: StickyNote, to: '/cortex/workspace/memos' },
      { labelKey: 'nav.personalWorkspace.directory', icon: Contact, to: '/cortex/workspace/directory' },
      { labelKey: 'nav.personalWorkspace.settings', icon: Settings, to: '/cortex/workspace/settings' },
    ],
  },
  {
    to: '/cortex/departments',
    icon: Building2,
    labelKey: 'nav.departments',
    children: departmentConfigs.map((department) => ({
      labelKey: department.navKey,
      icon: department.icon,
      to: `/cortex/departments/${department.slug}`,
    })),
  },

  {
    to: '/cortex/chat',
    icon: MessageSquare,
    labelKey: 'nav.chat',
    children: [
      { labelKey: 'nav.chat.new', icon: MessageSquarePlus, to: '/cortex/chat' },
      { labelKey: 'nav.chat.directory', icon: Users, to: '/cortex/chat/directory' },
      { labelKey: 'nav.chat.leave', icon: ClipboardList, to: '/cortex/chat/leave' },
      { labelKey: 'nav.chat.overtime', icon: Clock, to: '/cortex/chat/overtime' },
      { labelKey: 'nav.chat.trip', icon: Plane, to: '/cortex/chat/trip' },
      { labelKey: 'nav.chat.outing', icon: MapPin, to: '/cortex/chat/outing' },
      { labelKey: 'nav.chat.history', icon: History, to: '/cortex/chat/history' },
    ],
  },
  {
    to: '/cortex/collaboration',
    icon: MessagesSquare,
    labelKey: 'nav.collaboration',
    children: [
      { labelKey: 'nav.collaboration.announcements', icon: Megaphone, to: '/cortex/collaboration/announcements' },
      { labelKey: 'nav.collaboration.workflows', icon: FileClock, to: '/cortex/collaboration/workflows' },
      { labelKey: 'nav.collaboration.calendar', icon: Calendar, to: '/cortex/collaboration/calendar' },
      { labelKey: 'nav.collaboration.bookings', icon: CalendarDays, to: '/cortex/collaboration/bookings' },
      { labelKey: 'nav.collaboration.channels', icon: Hash, to: '/cortex/collaboration/channels' },
      { labelKey: 'nav.collaboration.issues', icon: ClipboardList, to: '/cortex/collaboration/issues' },
      { labelKey: 'nav.collaboration.myIssues', icon: UserCheck, to: '/cortex/collaboration/my-issues' },
      { labelKey: 'nav.collaboration.projects', icon: FolderKanban, to: '/cortex/collaboration/projects' },
      { labelKey: 'nav.collaboration.circulars', icon: Send, to: '/cortex/collaboration/circulars' },
      { labelKey: 'nav.collaboration.discussions', icon: MessagesSquare, to: '/cortex/collaboration/discussions' },
    ],
  },
  {
    to: '/cortex/documents',
    icon: FileText,
    labelKey: 'nav.documents',
    children: [
      { labelKey: 'nav.documents.upload', icon: Upload, to: '/cortex/documents' },
      { labelKey: 'nav.documents.content', icon: Library, to: '/cortex/documents/content' },
      { labelKey: 'nav.documents.shared', icon: FolderKanban, to: '/cortex/documents/shared' },
      { labelKey: 'nav.documents.forms', icon: ClipboardList, to: '/cortex/documents/forms' },
      { labelKey: 'nav.documents.iso', icon: ShieldCheck, to: '/cortex/documents/iso' },
      { labelKey: 'nav.documents.list', icon: List, to: '/cortex/documents/list' },
      { labelKey: 'nav.documents.recent', icon: Clock, to: '/cortex/documents/recent' },
      { labelKey: 'nav.documents.favorites', icon: Bookmark, to: '/cortex/documents/favorites' },
      { labelKey: 'nav.documents.indexing', icon: FolderSearch, to: '/cortex/documents/indexing' },
      { labelKey: 'nav.documents.trash', icon: Trash2, to: '/cortex/documents/trash' },
    ],
  },
  {
    to: '/cortex/projects',
    icon: FolderKanban,
    labelKey: 'nav.projects',
    children: [
      { labelKey: 'nav.projects.information', icon: Link2, to: '/cortex/projects/information' },
      { labelKey: 'nav.projects.gantt', icon: BarChart3, to: '/cortex/projects/gantt' },
      { labelKey: 'nav.projects.calendar', icon: Calendar, to: '/cortex/projects/calendar' },
      { labelKey: 'nav.projects.milestones', icon: Flag, to: '/cortex/projects/milestones' },
      { labelKey: 'nav.projects.kanban', icon: FolderKanban, to: '/cortex/projects/kanban' },
      { labelKey: 'nav.projects.meetings', icon: MessagesSquare, to: '/cortex/projects/meetings' },
      { labelKey: 'nav.projects.emails', icon: Mail, to: '/cortex/projects/emails' },
      { labelKey: 'nav.projects.budget', icon: CircleDollarSign, to: '/cortex/projects/budget' },
      { labelKey: 'nav.projects.people', icon: Users, to: '/cortex/projects/people' },
      { labelKey: 'nav.projects.requirements', icon: ClipboardList, to: '/cortex/projects/requirements' },
      { labelKey: 'nav.projects.risks', icon: AlertTriangle, to: '/cortex/projects/risks' },
      { labelKey: 'nav.projects.audits', icon: ClipboardCheck, to: '/cortex/projects/audits' },
      { labelKey: 'nav.projects.reports', icon: FileText, to: '/cortex/projects/reports' },
      { labelKey: 'nav.projects.resources', icon: Users, to: '/cortex/projects/resources' },
      { labelKey: 'nav.projects.customers', icon: Building2, to: '/cortex/projects/customers' },
      { labelKey: 'nav.projects.vendors', icon: Truck, to: '/cortex/projects/vendors' },
    ],
  },
  {
    to: '/cortex/search',
    icon: Search,
    labelKey: 'nav.search',
    children: [
      { labelKey: 'nav.search.fulltext', icon: Search, to: '/cortex/search' },
      { labelKey: 'nav.search.hybrid', icon: Layers, to: '/cortex/search/hybrid' },
    ],
  },
  {
    to: '/cortex/knowledge',
    icon: Library,
    labelKey: 'nav.knowledgeCenter',
    children: [
      { labelKey: 'nav.knowledgeCenter.documents', icon: FileText, to: '/cortex/knowledge/documents' },
      { labelKey: 'nav.knowledgeCenter.categories', icon: FolderCog, to: '/cortex/knowledge-categories' },
      { labelKey: 'nav.knowledgeCenter.review', icon: ClipboardCheck, to: '/cortex/knowledge/review' },
      { labelKey: 'nav.knowledgeCenter.faq', icon: CircleHelp, to: '/cortex/knowledge/faq' },
      { labelKey: 'nav.knowledgeCenter.experts', icon: UserRoundSearch, to: '/cortex/knowledge/experts' },
      { labelKey: 'nav.knowledgeCenter.community', icon: Users, to: '/cortex/knowledge/community' },
    ],
  },
  {
    to: '/cortex/graph',
    icon: Share2,
    labelKey: 'nav.graph',
    children: [
      { labelKey: 'nav.graph.overview', icon: Network, to: '/cortex/graph' },
      { labelKey: 'nav.graph.community', icon: Users, to: '/cortex/graph/community' },
      { labelKey: 'nav.graph.isolated', icon: AlertTriangle, to: '/cortex/graph/isolated' },
      { labelKey: 'nav.graph.new', icon: Plus, to: '/cortex/graph/research' },
      { labelKey: 'nav.graph.history', icon: Clock, to: '/cortex/graph/history' },
    ],
  },
  {
    to: '/cortex/orgManagement',
    icon: FlaskConical,
    labelKey: 'nav.orgManagement',
    children: [
      { labelKey: 'nav.orgManagement.dashboard', icon: LayoutDashboard, to: '/cortex/orgManagement/dashboard' },
      { labelKey: 'nav.orgManagement.vendors', icon: Truck, to: '/cortex/orgManagement/vendors' },
      { labelKey: 'nav.orgManagement.customers', icon: Building2, to: '/cortex/orgManagement/customers' },
      { labelKey: 'nav.orgManagement.products', icon: Package, to: '/cortex/orgManagement/products' },
      { labelKey: 'nav.orgManagement.resources', icon: Users, to: '/cortex/orgManagement/resources' },
      { labelKey: 'nav.orgManagement.meetings', icon: CalendarDays, to: '/cortex/orgManagement/meetings' },
      { labelKey: 'nav.orgManagement.finance', icon: CircleDollarSign, to: '/cortex/orgManagement/finance' },
      { labelKey: 'nav.orgManagement.contracts', icon: FileText, to: '/cortex/orgManagement/contracts' },
      { labelKey: 'nav.orgManagement.assets', icon: MonitorCog, to: '/cortex/orgManagement/assets' },
      { labelKey: 'nav.orgManagement.inventory', icon: Boxes, to: '/cortex/orgManagement/inventory' },
      { labelKey: 'nav.orgManagement.warehouse', icon: Warehouse, to: '/cortex/orgManagement/warehouse' },
    ],
  },
  {
    to: '/cortex/hr',
    icon: UserRoundSearch,
    labelKey: 'nav.hrPortal',
    children: [
      { labelKey: 'nav.hr.personnel', icon: UserCheck, to: '/cortex/hr/personnel' },
      { labelKey: 'nav.hr.attendance', icon: CalendarClock, to: '/cortex/hr/attendance' },
      { labelKey: 'nav.hr.payroll', icon: CircleDollarSign, to: '/cortex/hr/payroll' },
    ],
  },
  {
    to: '/cortex/workflows',
    icon: Workflow,
    labelKey: 'nav.workflows',
    children: [
      { labelKey: 'nav.workflows.overview', icon: Network, to: '/cortex/workflows/overview' },
      { labelKey: 'nav.workflows.designer', icon: Workflow, to: '/cortex/workflows/designer' },
      { labelKey: 'nav.workflows.screenDesigner', icon: LayoutGrid, to: '/cortex/workflows/screen-designer' },
      { labelKey: 'nav.workflows.definitions', icon: GitBranch, to: '/cortex/workflows/definitions' },
      { labelKey: 'nav.workflows.tasks', icon: UserCheck, to: '/cortex/workflows/tasks' },
      { labelKey: 'nav.workflows.history', icon: FileClock, to: '/cortex/workflows/history' },
      { labelKey: 'nav.workflows.instances', icon: FileClock, to: '/cortex/workflows/instances' },
      { labelKey: 'nav.workflows.monitoring', icon: Activity, to: '/cortex/workflows/monitoring' },
    ],
  },
  {
    to: '/cortex/ai-models',
    icon: Cpu,
    labelKey: 'nav.aiModels',
    children: [
      { labelKey: 'nav.aiModels.embedding', icon: Layers, to: '/cortex/ai-models/embedding' },
      { labelKey: 'nav.aiModels.reranking', icon: ArrowUpDown, to: '/cortex/ai-models/reranking' },
    ],
  },
  {
    to: '/cortex/settings',
    icon: Settings,
    labelKey: 'nav.settings',
    children: [
      { labelKey: 'nav.settings.system', icon: Sliders, to: '/cortex/settings/system' },
      { labelKey: 'nav.settings.users', icon: Users, to: '/cortex/settings/users' },
      { labelKey: 'nav.settings.departments', icon: Building2, to: '/cortex/settings/departments' },
      { labelKey: 'nav.settings.roles', icon: UserCheck, to: '/cortex/settings/roles' },
      { labelKey: 'nav.settings.permissions', icon: ShieldCheck, to: '/cortex/settings/permissions' },
      { labelKey: 'nav.settings.menus', icon: List, to: '/cortex/settings/menus' },
      { labelKey: 'nav.settings.aiManagement', icon: Cpu, to: '/cortex/settings/ai-management' },
      { labelKey: 'nav.settings.channels', icon: Hash, to: '/cortex/settings/channels' },
      { labelKey: 'nav.settings.schedules', icon: CalendarDays, to: '/cortex/settings/schedules' },
      { labelKey: 'nav.settings.autoApprove', icon: UserCheck, to: '/cortex/settings/auto-approve' },
      { labelKey: 'nav.settings.autoComplete', icon: Sparkles, to: '/cortex/settings/auto-complete' },
      { labelKey: 'nav.settings.notifications', icon: Bell, to: '/cortex/settings/notifications' },
      { labelKey: 'nav.settings.commitMessages', icon: GitBranch, to: '/cortex/settings/commit-messages' },
      { labelKey: 'nav.settings.sandboxes', icon: Box, to: '/cortex/settings/sandboxes' },
      { labelKey: 'nav.settings.languages', icon: Globe, to: '/cortex/settings/languages' },
      { labelKey: 'nav.settings.about', icon: CircleHelp, to: '/cortex/settings/about' },
    ],
  },
];
